services:
    metamodels.filter_range.factory:
        class: MetaModels\FilterRangeBundle\FilterSetting\RangeFilterSettingTypeFactory
        tags:
          - { name: metamodels.filter_factory }

    metamodels.filter_range.date_factory:
        class: MetaModels\FilterRangeBundle\FilterSetting\RangeDateFilterSettingTypeFactory
        tags:
          - { name: metamodels.filter_factory }

    metamodels.filter_range.listener.decode_property_value_for_widget:
        class: MetaModels\FilterRangeBundle\EventListener\DcGeneral\Table\FilterSetting\DecodePropertyValueForWidgetListener
        tags:
          - { name: kernel.event_listener, event: dc-general.view.contao2backend.decode-property-value-for-widget, method: handle}

    metamodels.filter_range.listener.encode_property_value_from_widget:
        class: MetaModels\FilterRangeBundle\EventListener\DcGeneral\Table\FilterSetting\EncodePropertyValueFromWidgetListener
        tags:
          - { name: kernel.event_listener, event: dc-general.view.contao2backend.encode-property-value-from-widget, method: handle}

    metamodels.filter_range.listener.get_property_options:
        class: MetaModels\FilterRangeBundle\EventListener\DcGeneral\Table\FilterSetting\GetPropertyOptionsListener
        tags:
          - { name: kernel.event_listener, event: dc-general.view.contao2backend.get-property-options, method: handle}
